using System.Collections.Generic;
using UnityEngine;

// Registry of every complete item, so the bank can resolve "component A + component B"
// into the forged result. Kept as an asset and regenerated by CompleteItemGenerator.
[CreateAssetMenu(fileName = "ItemRecipeBook", menuName = "Autobattler/Items/Recipe Book")]
public class ItemRecipeBook : ScriptableObject
{
    public List<ItemComponentData> completeItems = new List<ItemComponentData>();

    public ItemComponentData FindRecipe(ItemComponentData a, ItemComponentData b)
    {
        if (a == null || b == null) return null;
        if (a.isCompleteItem || b.isCompleteItem) return null; // only raw components combine

        foreach (ItemComponentData item in completeItems)
            if (item != null && item.MatchesRecipe(a, b)) return item;

        return null;
    }
}
